### PR TITLE
Word dictionary fixes

### LINKED ISSUE #32: Add confirmation of adding, editing and removing words in UI
Currently when user adds a new word, edits or removes currently existing one there is no visible confirmation (or error) in the frontend UI. We should add such a confirmation so user is 100% sure of the action success/failure.
This confirmation can be in the form of a mobile-like panel with appropriate message

### LINKED ISSUE #36: Validate new and edited word fields when updating words dictionary
Currently when user wants to add a new word or edits a currently existing one there is no validation logic and thus user can add a word with empty name, undefined category or without any description. Updating word is similar but additionally we should check if any changes were performed before calling REST API.

### LINKED ISSUE #37: Add state control in words dictionary page
Currently we are checking if word service is available only when receiving lost of words and dictionary init.
We should also update UI state of words dictionary even when service gets disconnected during words usage.

### PR DESCRIPTION
**Pull request by piopon**
This patch fixes word dictionary issues:

1. fixes #32 - new word action confirmation toast appear when adding, editing and removing word
image
image
image

2. fixes #37 - when word service goes oflline during word action an overlay will appear and inform the user about status
image
image

3. fixes #36 - when user does not provide a new/edited word component then REST API is not triggered. Instead a toast with validation result is displayed
image
image
image

### CODE REVIEW

File: frontend/js/words.js [hunk 1]
```diff
@@ -87,9 +98,11 @@ function removeWord(name) {
 function refreshWordsCallback(err, data) {
   if (err) {
     console.log("ERROR: " + err);
```
Comment (piopon) [inline frontend/js/words.js:100]: It would be a good idea to show error messages in a toast.

Comment (piopon) [reply frontend/js/words.js]: Updated.

**Comment by piopon** [comment]
Updated toast colors and messages.
When everything works correctly the background will be green as shown in the images below:
image
image
image

When there is an UI error (validation, etc.) then te toast will be orange:
image
image
image
image

Finally, when there is a backend service error / connection issue then the toast will be displayed in red:
image
image
