### PR TITLE
UI fixes: added question status & nav + updated hover + fixed add word refresh

### LINKED ISSUE #14: Update the hover style for top-menu buttons
Current on-hover style for top-menu items is not looking good:
image
We should update it and maybe just add some shadow or other image effect

### LINKED ISSUE #22: Add current quiz status UI
Currently there is no visual indicator informing the user about current quiz progress.
The only information is the current question number and total questions count on the top of the page.
We should add some kind of bar representing all questions + markings about correct and incorrect answer:
image

### PR DESCRIPTION
**Pull request by piopon**
Updated GUI in quiz and words pages:
- added navigation and status bar for quiz questions
  image
- updated main menu button hover effect
  image
- fixed not needed page refresh when adding new word (and service is not available)
  image
- updated result percentage to have max 2 digits in value
  image

This patch fixes #14, fixes #22

### CODE REVIEW

File: frontend/js/quiz.js [hunk 1]
```diff
@@ -35,9 +36,9 @@ function startQuiz() {
  * @param {Integer} state current loading state (from: START_QUIZ_OK, START_QUIZ_LOAD, START_QUIZ_ERROR)
  */
 function startQuizUpdateUiState(state) {
-  let startQuizBtn = document.getElementById("quiz-mode-start");
-  let startQuizInfo = document.getElementById("quiz-extra-info");
-  if (startQuizBtn === null) return;
+  let startQuizBtn = document.getElementById("quiz-mode-controls-start");
+  let startQuizInfo = document.getElementById("quiz-mode-controls-info");
+  if (startQuizBtn === null || startQuizInfo === null) return;
```
Comment (piopon) [inline frontend/js/quiz.js:41]: Verify if this case is possible

File: frontend/js/quiz.js [hunk 2]
```diff
@@ -243,6 +246,23 @@ function getAnswerButtonClass(isNewQuestion, isAnswerCorrect) {
   return isAnswerCorrect ? "question-option-btn-ok" : "question-option-btn-nok";
 }
 
+/**
+ * Method used to create and update question depending on current questionStatus array contents
+ *
+ * @param {Boolean} enableStatusNavigation flag indicating if status should also have question navigation functionalities
```
Comment (piopon) [inline frontend/js/quiz.js:252]: Add info about default value

File: frontend/js/quiz.js (hunk 1 above)
Comment (piopon) [reply frontend/js/quiz.js:41]: Current solution is correct.

File: frontend/js/quiz.js (hunk 2 above)
Comment (piopon) [reply frontend/js/quiz.js]: Updated.
