### PR TITLE
Quiz duplicates fix

### LINKED ISSUE #12: Duplicated word question in the same quiz instance
There is a bug with the same word question in a single quiz contest.

**For example:**
image
image

As one can see we have two exactly the same words next to each other (question 8 and 9). Even if this case would be in the first and last question it's a bug which should be fixed so every quiz will contain ALL DIFFERENT words

### LINKED ISSUE #13: One question contains couple the same answers
Currently it's possible to have a couple of the same answers for the same word
image
We should fix it by rewriting the quiz logic so each answer is unique

### PR DESCRIPTION
**Pull request by piopon**
Fixed duplicated words (fixes #12) and answers issues (fixes #13).
- added remove rounds duplicates and replacing them with different rounds (tested even with 3 duplicates)
- added remove round answer duplicates (only correct answer and one invalid could duplicate)

### CODE REVIEW

File: backend/src/main/scala/pl/smtc/smartwords/service/QuizService.scala [hunk 1]
```diff
@@ -87,20 +87,46 @@ class QuizService(quizDB: QuizDatabase, wordDB: WordDatabase) {
    * Method used to generate a new round object
    * @return generated round object with random word and 4 answer options
    */
-  private def generateRound(): Round = {
-    val word: Word = wordDB.getWord(Random.nextInt(wordDB.getWords.length)).get
+  private def generateRound(forbiddenWords: List[String] = List.empty): Round = {
```
Comment (piopon) [inline backend/src/main/scala/pl/smtc/smartwords/service/QuizService.scala:90]: Update method description

Comment (piopon) [reply backend/src/main/scala/pl/smtc/smartwords/service/QuizService.scala:91]: Updated.
